apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-app
  namespace: monitoring
  labels:
    release: monitoring          # 🔴 THIS WAS MISSING
spec:
  selector:
    matchLabels:
      app: spring-k8-demo
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
